### ISSUE TITLE
登录界面适配问题

### ISSUE THREAD

**Issue by salutdamour** [YizheYang/Book#6]
- 填写用户名处的文本框可以换行，应该设置好固定大小，增加用户体验
![image](https://user-images.githubusercontent.com/57986506/143670320-5d3118b9-80bc-48e2-bf7a-fd48665b49fb.png)
- 文本框左侧提示文字无法显示
![image](https://user-images.githubusercontent.com/57986506/143670329-db7969a6-df35-4bd8-ba72-eb8f8629fa1e.png)

**Comment by YizheYang** [comment]
1.0.3已解决
